main: com.cavetale.funtools.FunToolsPlugin
name: FunTools
version: 0.1
api-version: 1.13
description: Custom Tools for Survival Players
author: StarTux
website: https://cavetale.com
depend: [Dirty]
softdepend: []
